### ISSUE TITLE
Empty command

### ISSUE THREAD

**Issue by stochmial** [camptocamp/puppet-archive#50]
After upgrading from 0.5.x to 0.6.1 we have
Archive::Extract[liquibase-3.3.2]/Exec[liquibase-3.3.2 unpack]/returns (err): change from notrun to 0 failed: Could not find command ''

**Comment by fatmcgav** [comment]
Have just hit the same issue... 

I think it's related to PR #45, specifically https://github.com/camptocamp/puppet-archive/blob/5fa16c438ce52231766d40c6795b4cb32852f780/manifests/extract.pp#L59

Gav

**Comment by jschilperoord** [comment]
Also hit this issue. I pinned to a 0.5.x version for now.

**Comment by baboune** [comment]
Same issue.

**Comment by pennycoders** [comment]
Hi,

I've submitted a pull request today, which fixes the issue.

Hope it'll go through. The problem was there was an extra space in the extraction command, so the full command evaluated to " extract cnd"
