### ISSUE TITLE
re-download source file

### ISSUE THREAD

**Issue by mmarseglia** [camptocamp/puppet-archive#52]
I ran into an issue where the source file was downloaded incorrectly.  I specified the wrong URL but curl was able to download the server's response.  Subsequent puppet agent runs would not re-download the file.

Is there an option to re-download a file? or delete a file after it has been downloaded?

**Comment by jgrumboe** [comment]
This PR seems to have a different code base than this one. Seems like the voxpupulli/puppet-archive.

**Comment by mmarseglia** [comment]
My mistake!
