### ISSUE TITLE
path fact?

### ISSUE THREAD

**Issue by alexharv074** [camptocamp/puppet-archive#65]
I get the following failure when I compile via rspec-puppet:

```
error during compilation: Validation of Exec[download archive kibana-4.3.1-linux-x64.tar.gz and check sum] failed: 'curl  -s -S   -o /usr/src/kibana-4.3.1-linux-x64.tar.gz 'http://myplace/kibana/4.3.1/kibana-4.3.1-x64.tar.gz'' is not qualified and no path was specified. Please qualify the command or specify a path. at spec/fixtures/modules/archive/manifests/download.pp:171
```

Meanwhile in a627bc3c4dafb6f24cbccd59caa85e3414d3d3be archive::download now defaults to a fact or global scope variable $::path? 

```puppet
define archive::download (
...
  $path=$::path,
) {
```

Anyone know what the thinking is here? ping  @raphink

**Comment by alexharv074** [comment]
ping @raphink  I'm not sure if this is a bug or a feature.  Thanks.

**Comment by raphink** [comment]
When using rspec-puppet, facts are not available so they can be mocked. I'd recommend you have a look at https://github.com/camptocamp/rspec-puppet-facts for easy mocking of known platforms.

**Comment by alexharv074** [comment]
Thanks.
