### ISSUE TITLE
File permissions overriden on every puppet run

### ISSUE THREAD

**Issue by yaumsnus** [camptocamp/puppet-archive#71]
I need to set particular permissions on an extracted directory. But on every puppet run, archive extract it once again and overide permissions that I try to maintain...

```
archive { 'gaussian':
    ensure    =>  present,
    url       =>  'http://myfileserver/sources/gaussian_09.tgz',
    target    =>  '/opt',
    extension => "tgz",
    checksum  =>  false,
  }

file { '/opt/gaussian':
    ensure  =>  directory,
    owner   =>  "root",
    group   =>  "users",
    recurse =>  true,
    mode    =>  "0750",
    require => Archive['gaussian'],
}
```

**Comment by Yamakasi** [comment]
I have the same issue and I'm trying to apply some unless => but that doesn't work.

Any clue ?

**Comment by jgrumboe** [comment]
In extract.pp there's a warning included:
```
# The parameter *$root_dir* must be used if the root directory of the archive
# is different from the name of the archive *$name*. To extract the name of
# the root directory use the commands "tar tf archive.tar.gz" or
# "unzip -l archive.zip"
```
So if your file gaussian_09.tgz doesn't include a directory also named gaussian_09, you will need to set $root_dir as parameter to the actual directory name inside the archive.
